name: ${project.build.name}
main: com.bryankeiren.fjord.Fjord
version: ${project.build.version}
load: STARTUP

commands:
    fjord:
        aliases: [fj]
        description: Allows you to access Fjord functions.
        usage: /<command>

permissions:
  fjord.*:
    description: Provides access to all Fjord commands.
    children:
      fjord.version: true
  fjord.version:
    default: op
    description: Allows you to view the current Fjord version.
